// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v2alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nuodb) DeepCopyInto(out *Nuodb) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nuodb.
func (in *Nuodb) DeepCopy() *Nuodb {
	if in == nil {
		return nil
	}
	out := new(Nuodb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Nuodb) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NuodbInsightsServer) DeepCopyInto(out *NuodbInsightsServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NuodbInsightsServer.
func (in *NuodbInsightsServer) DeepCopy() *NuodbInsightsServer {
	if in == nil {
		return nil
	}
	out := new(NuodbInsightsServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NuodbInsightsServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NuodbInsightsServerList) DeepCopyInto(out *NuodbInsightsServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NuodbInsightsServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NuodbInsightsServerList.
func (in *NuodbInsightsServerList) DeepCopy() *NuodbInsightsServerList {
	if in == nil {
		return nil
	}
	out := new(NuodbInsightsServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NuodbInsightsServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NuodbInsightsServerSpec) DeepCopyInto(out *NuodbInsightsServerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NuodbInsightsServerSpec.
func (in *NuodbInsightsServerSpec) DeepCopy() *NuodbInsightsServerSpec {
	if in == nil {
		return nil
	}
	out := new(NuodbInsightsServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NuodbInsightsServerStatus) DeepCopyInto(out *NuodbInsightsServerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NuodbInsightsServerStatus.
func (in *NuodbInsightsServerStatus) DeepCopy() *NuodbInsightsServerStatus {
	if in == nil {
		return nil
	}
	out := new(NuodbInsightsServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NuodbList) DeepCopyInto(out *NuodbList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Nuodb, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NuodbList.
func (in *NuodbList) DeepCopy() *NuodbList {
	if in == nil {
		return nil
	}
	out := new(NuodbList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NuodbList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NuodbSpec) DeepCopyInto(out *NuodbSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NuodbSpec.
func (in *NuodbSpec) DeepCopy() *NuodbSpec {
	if in == nil {
		return nil
	}
	out := new(NuodbSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NuodbStatus) DeepCopyInto(out *NuodbStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NuodbStatus.
func (in *NuodbStatus) DeepCopy() *NuodbStatus {
	if in == nil {
		return nil
	}
	out := new(NuodbStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NuodbYcsbWl) DeepCopyInto(out *NuodbYcsbWl) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NuodbYcsbWl.
func (in *NuodbYcsbWl) DeepCopy() *NuodbYcsbWl {
	if in == nil {
		return nil
	}
	out := new(NuodbYcsbWl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NuodbYcsbWl) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NuodbYcsbWlList) DeepCopyInto(out *NuodbYcsbWlList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NuodbYcsbWl, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NuodbYcsbWlList.
func (in *NuodbYcsbWlList) DeepCopy() *NuodbYcsbWlList {
	if in == nil {
		return nil
	}
	out := new(NuodbYcsbWlList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NuodbYcsbWlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NuodbYcsbWlSpec) DeepCopyInto(out *NuodbYcsbWlSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NuodbYcsbWlSpec.
func (in *NuodbYcsbWlSpec) DeepCopy() *NuodbYcsbWlSpec {
	if in == nil {
		return nil
	}
	out := new(NuodbYcsbWlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NuodbYcsbWlStatus) DeepCopyInto(out *NuodbYcsbWlStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NuodbYcsbWlStatus.
func (in *NuodbYcsbWlStatus) DeepCopy() *NuodbYcsbWlStatus {
	if in == nil {
		return nil
	}
	out := new(NuodbYcsbWlStatus)
	in.DeepCopyInto(out)
	return out
}
